services:
  postgres:
    image: 'postgres:16'
    container_name: fraud-detection-postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  sagemaker-model:
    image: ghcr.io/itumelengmanota/fraud-detection-model:latest
    container_name: fraud-detection-model
    ports:
      - '8080:8080'
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 120s
    environment:
      - MODEL_NAME=fraud-detection-model
      - MODEL_VERSION=1.0.0

  mockoon:
    image: 'mockoon/cli:latest'
    container_name: fraud-detection-mockoon
    ports:
      - '3001:3000'
    restart: unless-stopped
    volumes:
      - ./mockoon/data.json:/data/data.json
    command: ['--data', '/data/data.json']

  redis:
    image: 'redis:7.4'
    container_name: fraud-detection-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  kafka:
    image: 'apache/kafka:3.8.1'
    container_name: fraud-detection-kafka
    ports:
      - '9092:9092'
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  apicurio-registry:
    image: 'apicurio/apicurio-registry:3.0.6'
    container_name: fraud-detection-apicurio-registry
    ports:
      - '8081:8080'
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_KIND: 'inmemory'
    depends_on:
      - kafka

  apicurio-registry-ui:
    image: 'apicurio/apicurio-registry-ui:3.0.6'
    container_name: fraud-detection-apicurio-registry-ui
    ports:
      - '8082:8080'
    restart: unless-stopped
    environment:
      REGISTRY_API_URL: 'http://apicurio-registry:8080/apis/registry/v2'
    depends_on:
      - apicurio-registry

  kafka-ui:
    image: 'provectuslabs/kafka-ui:v0.7.2'
    container_name: fraud-detection-kafka-ui
    ports:
      - '8083:8080'
    restart: unless-stopped
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://apicurio-registry:8080/apis/ccompat/v7'
    depends_on:
      - kafka
      - apicurio-registry

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: fraud-detection-keycloak
    command: start-dev
#    command: start-dev --import-realm
#    volumes:
#      - ./keycloak-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8180:8080'
    restart: unless-stopped

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.0.7
#    container_name: fraud-detection-keycloak
#    command:
#      - start-dev
#      - --import-realm
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: postgres
#    ports:
#      - "8180:8080"
##      - '8443:8443'
#    restart: unless-stopped
#    volumes:
#      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
##      - ./keycloak-config/server.crt.pem:/opt/keycloak/conf/server.crt.pem
##      - ./keycloak-config/server.key.pem:/opt/keycloak/conf/server.key.pem
#    depends_on:
#      - postgres

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    container_name: fraud-detection-grafana-lgtm
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    restart: unless-stopped


